title: Business Card
description: A simple business card online.
baseurl: /business-card
url: ''
author: © 2018 Jεan Sacren

timezone: America/Denver
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
